### PR TITLE
Update base64 version to 1.1.2

### PR DESCRIPTION
**Pull request by jbrophy17**

### CODE REVIEW

**Comment by lolgear** [comment]
it seems that Kiwi start this frustration.
Your pull request fail and if I restart this pull request, it will pass tests.
It seems that Kiwi can't verify dictionaries first time?

**Comment by jbrophy17** [comment]
Yeah I've noticed that as well, even though it prints out the 2 dictionaries it's comparing and they are equal

**Comment by lolgear** [comment]
this one - no answer :/

https://github.com/kiwi-bdd/Kiwi/issues/668

**Comment by lolgear** [comment]
@jbrophy17 could you review methods in NSData and NSString categories ( +JWT )? They are connected to this task #43

**Comment by lolgear** [comment]
@jbrophy17 maybe these categories should be removed or simplified, for example, delegating methods to Base64 library or so

**Comment by jbrophy17** [comment]
The Base64 library doesn't offer Base64UrlEncoding, so the categories are still needed I think

**Comment by lolgear** [comment]
@jbrophy17 check https://github.com/ekscrypto/Base64/releases/tag/1.1

**Comment by jbrophy17** [comment]
Oh my bad, will update

**Comment by jbrophy17** [comment]
Removed the JWT categories, Base64 covered all the cases except for JSON object creation, which probably doesn't really need a category for it.

Also sort of snuck an update to encoding / decoding in this. Algorithms can now optionally support encoding / decoding using NSData as parameters for payload & key

**Comment by lolgear** [comment]
@jbrophy17 interesting!

**Comment by lolgear** [comment]
@jbrophy17 also, please, check `JWTBuilder jwtAlgorithm` getter, is it overloaded fine? maybe trouble with it and it should be removed to clean getter ( or it is better to somehow hide complex `jwtSecret` by overloading it through `_jwtSecret ? [_jwtSecret baseURLEncoding] : _jwtSecretData` )

**Comment by jbrophy17** [comment]
I think the overloaded algorithm getter is fine, maybe in the future it could be changed to just always return `[JWTAlgorithmFactory algorithmByName:_jwtAlgorithmName` and then you would only have to worry about setting the algorithm name.

I also think keeping secret and secretData separate for now is fine. Maybe at some point in the future the <JWTAlgorithm> protocol could be changed to only take NSData arguments and then the secret getter could be changed to always return data

**Comment by lolgear** [comment]
#47

**Pull request merged**
