### PR TITLE
Missing claimsSet extraction added.

### PR DESCRIPTION
**Pull request by lolgear**
### New Pull Request Checklist

* [x] I have searched for a similar pull request in the [project](https://github.com/yourkarma/JWT/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

...
Possible fix of #158

### CODE REVIEW

**Comment by icedice** [comment]
Man you guys work fast 👍 
I've testet it and it works as expected. The only strange thing is that i now see this 
`Umbrella header for module 'JWT' does not include header 'JWTAlgorithmESBase.h'`
Which caused me not to be able to build because I set "treat warnings as errors".

**Comment by lolgear** [comment]
@icedice try latest master

**Comment by icedice** [comment]
It is working now, but I'm seeing this error:

/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTAlgorithmESBase.h'

**Comment by icedice** [comment]
Perfect. After forcing my podfile to use "e201ea5a2e2e8530b17e11cad08fda0e788a5a3f" it works perfectly. Thanks a lot!

**Pull request merged**
