### PR TITLE
Disable secret check when not used

### PR DESCRIPTION
**Pull request by kostassite**
If pass nil as secret to not validate the signature

### CODE REVIEW

**Comment by lolgear** [comment]
@kostassite, hi!
Could you provide examples when you need this?
JWT has headers for validation.
Special alg header value: 'none' could disable signature validations.
For this reason we have JWTAlgorithmNone and JWTAlgorithmFactory ( which return algorithms based on their names - alg headers values ).

**Comment by kostassite** [comment]
Hi
I am using the token for 2 things in my application.
1. As authorization when I am doing requests to my server, so the server need to validate the jwt.
2. To take some info from the jwt about the status of the user. I dont need to validate the jwt in this case because even if as client let the user do something with a hacked jwt, server will not allow it. 
So I need to keep the alg header but need to be able also to read the payload. Thats why I made secret param not required. Also I dont want to have the shared secret in my app and thats why cant use it “correct”.

Thanks
Kostas

**Comment by lolgear** [comment]
#36

**Comment by lolgear** [comment]
@kostassite, please, check version 1.1.2

**Comment by lolgear** [comment]
@kostassite I close pull request.
Fill free to open new one and also don't forget to check new versions.

**Pull request closed without merging**
