### PR TITLE
RS256 algorithm implementation

### PR DESCRIPTION
**Pull request by marcelo-schroeder**
This pull request adds the missing implementation for the RS256 algorithm. This allows JWT tokens to be signed by a certificate containing the private key and also allows for signature verification by using the certificate containing the public key. I have also added JWTAlgorithmRS256Tests which should help understand what the changes are about.

### CODE REVIEW

**Comment by lolgear** [comment]
@marcelo-schroeder hi! great job! but before merge I would like to ask you to fix breaking tests.
Also, could you add 384 and 512 versions? I think it would be simple with 256 implementation.

**Comment by marcelo-schroeder** [comment]
Thank you for getting started with this project.

Tests:
1) Sorry, I thought that RS tests didn't exist and also I tried to run the tests on my machine before even starting writing my tests and they failed, so I didn't bother running all of them again. What I did now was to remove JWTAlgorithmRS256Spec.m as all tests needed are now in JWTAlgorithmRS256Tests.m (sorry, I'm not familiar with Kiwi and I am very busy at the moment to try and learn it).
2) All tests now run fine on my machine and everything is checked in correctly, so I'm not sure why the Travis CI build is failing.

384, 512 versions:
Sorry but I am extremely busy at the moment and RS256 is all I need in a high profile project I am currently working on. I might do them at a later stage or maybe someone else can contribute.

**Comment by marcelo-schroeder** [comment]
Failed tests: it looks like the base64 URL encoding is different on the machine where the tests are running on... I'll see if I can come up with tests that are more portable.

**Comment by marcelo-schroeder** [comment]
Ok, I made the encoding tests more flexible (i.e. they don't depend on a hardcoded expected token) and everything is good now.

**Comment by lolgear** [comment]
#44

**Pull request merged**
