### PR TITLE
Support tvOS

### PR DESCRIPTION
**Pull request by gcesarmza**
### New Pull Request Checklist

* [X] I have searched for a similar pull request in the [project](https://github.com/yourkarma/JWT/pulls) and found none

* [X] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [X] I have added the required tests to prove the fix/feature I am adding
* [X] I have updated the documentation (if necessary)
* [X] I have run the tests and they pass
* [X] I have run the lint and it passes (`pod lib lint`)

Before merge, please, assure that your commits are grouped.
Please, don't make several PRs with single commit, group PRs into one if possible.

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Fixes issue #216

### CODE REVIEW

**Comment by lolgear** [comment]
Could you add tests and TravisCI entries for `tvOS`?

**Comment by gcesarmza** [comment]
I didn't add any tests, just verified it compiles locally. 
I can update the test project and update the PR

**Comment by gcesarmza** [comment]
Done!

**Comment by lolgear** [comment]
@gcesarmza Looks great!

**Pull request merged**
