### PR TITLE
Make headers public so that framework can actually be used in ObjC

### PR DESCRIPTION
**Pull request by sinbad**
I couldn't use this library in ObjC because the headers are required to be included in the Framework. Fixed that.

### CODE REVIEW

**Comment by lolgear** [comment]
@sinbad Hi! Thanks for PR!
Did you change all related targets?

**Comment by sinbad** [comment]
AFAICT the other targets (JWT_macOS etc) don't have any build rules at all and aren't doing anything.

**Comment by lolgear** [comment]
@sinbad I think that they are a part of Carthage deployment.

**Comment by sinbad** [comment]
Yeah, but unlike other Carthage projects they don't seem to have anything in them, not even dependencies. I have no idea how they're working right now. I don't know much about Carthage but have pulled JWT with Carthage after and the headers appeared, so  ¯\_(ツ)_/¯

**Comment by lolgear** [comment]
@sinbad They only used in Travis CI, oh :(
Maybe later they should be removed from project.

**Pull request merged**
