### PR TITLE
can decode tokens without verifying signatures for unknown algorithms

### PR DESCRIPTION
**Pull request by activescott**

### CODE REVIEW

**Comment by klaaspieter** [comment]
I'm hesitant to add this functionality because not checking the signature is essentially undermining one of  promises of JWT. Can you explain why this is needed? 

Have you looked at using `JWTAlgorithmNone`?

**Comment by activescott** [comment]
I totally understand your concern. However, I was trying to decode an RS256 token for which the signature implementation doesn't exist so the current implementation fails to decode the token entirely. I just wanted the values decoded while testing. Without this patch it fails with an error since the algorithm implementation doesn't exist.

Definitely not ideal to not validate the signature. However, I think offering an explicit choice to decode the token with an unknown signature algorithm is better than always failing and not offering the choice.

**Comment by lolgear** [comment]
@activescott could you provide RS256 algorithm implementation?
Also, cheating with tests is the last thing to do.

**Comment by activescott** [comment]
Since I do not need RS256 algorithm, I don't have the implementation and don't need it. I wasn't cheating anywhere, I was only testing an endpoint with code that wasn't production code, which happens to use RS256 and I wanted to be able to see the values inside the token. Currently the library completely fails on the token and IMHO should not - as long as the user explicitly takes action to decode the token without validation which is why my PR did.

**Comment by lolgear** [comment]
@activescott, so, you can look at implementation and cheating with design by implementing subclass of None algorithm as RS256 algorithm ( seems possible ). Set algorithm name to 'rs256' and put it into a algorithm factory. Not too obvious, but oop-styled and good mockup solution for future algorithms' implementations

**Comment by lolgear** [comment]
#36

**Comment by lolgear** [comment]
@activescott please, check new version 1.1.2

**Comment by lolgear** [comment]
@activescott I close pull request. 
Fill free to open new one with further enhancements.

**Pull request closed without merging**
